IMG_SIZE = 256
BATCH_SIZE = 2
NUM_CLASSES = 3
NUM_EPOCHS = 10
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 3e-4
TRAIN_SPLIT = 0.8
VAL_SPLIT = 0.2
SEED = 42
LOG_INTERVAL = 10
NUM_WORKERS = 0

DATASET_PATH = "../Dataset/Stage1_Corrected"
CHECKPOINT_PATH = "cmsegnet_stage2.pt"
PREDICTION_DIR = "predictions"
 
DEFAULT_CAMERA_HEIGHT_MM = 680.0
DEFAULT_CAMERA_ANGLE_DEG = 35.0
